storage:
  local:
    type: file
    options:
      root: /var/www/html/image
  s3:
    type: s3
    options:
      region_name: us-east-1
      endpoint_url: https://s3.amazonaws.com
      bucket: image-bucket
      aws_access_key_id: aws_access_key_id
      aws_secret_access_key: aws_secret_access_key
transform:
  blog:
    - type: t
      options:
        - 800
        - 400
route:
  "/":
    storage: local
    transform:
      - r
      - original
  "/blog":
    storage: s3
    transform: blog
    expire: 86400
    save:
      JPEG:
        progressive: true
        quality: 80
  "/private":
    storage: local
    transform:  false